name: 🚀 Deploy Portfolio (Dev + Production)

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🟢 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci --include=optional

      - name: 🏗️ Build project
        run: npm run build

      - name: Save build
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/

  # ================= DEV =================
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get build
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: ☁️ Upload to DEV S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.DEV_S3_BUCKET }} --delete

  # ================= PRODUCTION =================
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get build
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/

      - name: 🔐 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      # 🔥 NEW: Create version
      - name: Set version
        run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV

      # 🔥 NEW: Upload to version folder
      - name: Upload versioned build
        run: |
          aws s3 sync dist/ s3://kishankewal.com/${{ env.VERSION }}

      # 🔥 NEW: Update current version
      - name: Update current folder
        run: |
          aws s3 sync s3://kishankewal.com/${{ env.VERSION }} s3://kishankewal.com/current

      # SAME: Invalidate CloudFront
      - name: 🔄 Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"